//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicDB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0NotDefined {
            get {
                object obj = ResourceManager.GetObject("_0NotDefined", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1Manual {
            get {
                object obj = ResourceManager.GetObject("_1Manual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2Normal {
            get {
                object obj = ResourceManager.GetObject("_2Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3AperturePriority {
            get {
                object obj = ResourceManager.GetObject("_3AperturePriority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4ShutterPriority {
            get {
                object obj = ResourceManager.GetObject("_4ShutterPriority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5CreativeProgram {
            get {
                object obj = ResourceManager.GetObject("_5CreativeProgram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6ActionProgram {
            get {
                object obj = ResourceManager.GetObject("_6ActionProgram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7PortraitMode {
            get {
                object obj = ResourceManager.GetObject("_7PortraitMode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8LandscapeMode {
            get {
                object obj = ResourceManager.GetObject("_8LandscapeMode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _SearchIcon {
            get {
                object obj = ResourceManager.GetObject("_SearchIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Pictures_Photographers (FK_Pic_ID, FK_PG_ID) 
        ///VALUES (@Pic_ID, @PG_ID);.
        /// </summary>
        public static string Add_Picture_To_Photographer {
            get {
                return ResourceManager.GetString("Add_Picture_To_Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Photographers WHERE PG_ID = @ID;.
        /// </summary>
        public static string DeletePhotographer_ID {
            get {
                return ResourceManager.GetString("DeletePhotographer_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Pictures WHERE FileName  = @FileName;.
        /// </summary>
        public static string DeletePicture_FileName {
            get {
                return ResourceManager.GetString("DeletePicture_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Pictures WHERE Pic_ID  = @ID;.
        /// </summary>
        public static string DeletePicture_ID {
            get {
                return ResourceManager.GetString("DeletePicture_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///	FROM Pictures as Pics
        ///		LEFT JOIN Photographers as PG ON PG.PG_ID = Pics.FK_PG_ID
        ///		LEFT JOIN EXIF ON EXIF_ID = Pics.FK_EXIF_ID
        ///		LEFT JOIN IPTC ON IPTC_ID = Pics.FK_IPTC_ID
        ///		LEFT JOIN Cameras ON Cam_ID = Pics.FK_Cam_ID
        ///
        ///	WHERE (@namePart IS NULL OR FileName LIKE &apos;%&apos; + @namePart + &apos;%&apos; )
        ///	
        ///		AND (@PG_PG_ID IS NULL OR @PG_PG_ID = PG.PG_ID)
        ///		AND (@PG_Birthday IS NULL OR @PG_Birthday = PG.BirthDay)
        ///		AND (@PG_FirstName IS NULL OR PG.FirstName LIKE &apos;%&apos; + @PG_FirstName + &apos;%&apos;)
        ///		AND (@PG_La [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Get_Search_Pictures {
            get {
                return ResourceManager.GetString("Get_Search_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Cameras;.
        /// </summary>
        public static string GetAll_Cameras {
            get {
                return ResourceManager.GetString("GetAll_Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM EXIF;.
        /// </summary>
        public static string GetAll_EXIF {
            get {
                return ResourceManager.GetString("GetAll_EXIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM IPTC;.
        /// </summary>
        public static string GetAll_IPTC {
            get {
                return ResourceManager.GetString("GetAll_IPTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Photographers;.
        /// </summary>
        public static string GetAll_Photographers {
            get {
                return ResourceManager.GetString("GetAll_Photographers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Pictures pics
        ///	LEFT JOIN Cameras ON pics.FK_Cam_ID = Cameras.Cam_ID
        ///	LEFT JOIN EXIF ON pics.FK_EXIF_ID = EXIF.EXIF_ID
        ///	LEFT JOIN IPTC ON pics.FK_IPTC_ID = IPTC.IPTC_ID
        ///	LEFT JOIN Photographers ON pics.FK_PG_ID = Photographers.PG_ID;.
        /// </summary>
        public static string GetAll_Pictures {
            get {
                return ResourceManager.GetString("GetAll_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ident_current(@TableName) + ident_incr(@TableName);.
        /// </summary>
        public static string GetNextID_TableName {
            get {
                return ResourceManager.GetString("GetNextID_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Cameras WHERE Cam_ID = @ID;.
        /// </summary>
        public static string GetOne_Camera_ID {
            get {
                return ResourceManager.GetString("GetOne_Camera_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Photographer WHERE PG_ID = @ID;.
        /// </summary>
        public static string GetOne_Photographer_ID {
            get {
                return ResourceManager.GetString("GetOne_Photographer_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Pictures 
        ///LEFT JOIN Cameras ON pics.FK_Cam_ID = Cameras.Cam_ID
        ///	LEFT JOIN EXIF ON pics.FK_EXIF_ID = EXIF.EXIF_ID
        ///	LEFT JOIN IPTC ON pics.FK_IPTC_ID = IPTC.IPTC_ID
        ///	LEFT JOIN Photographers ON pics.FK_PG_ID = Photographers.PG_ID
        ///WHERE Pic_ID = @ID;.
        /// </summary>
        public static string GetOne_Picture_ID {
            get {
                return ResourceManager.GetString("GetOne_Picture_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///   &lt;style&gt;
        ///      td {
        ///      width: 11em; 
        ///      border: 1px solid #000000;
        ///      word-wrap: break-word;
        ///      }
        ///      th {
        ///      text-align: left;
        ///      padding-right: 20px;
        ///      }
        ///      td {
        ///      padding: 20px;
        ///      }
        ///      td td {
        ///      padding: 5px;
        ///      }
        ///      table {
        ///      padding: 20px 20px 20px 20px;
        ///align:center;
        ///      }
        ///      .centered {
        ///      display: block;
        ///text-align: center;
        ///      margin-left: auto;
        ///      margin-right: auto;
        ///      }
        ///   &lt;/style&gt;
        ///   &lt;body&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string html_picture {
            get {
                return ResourceManager.GetString("html_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Cameras (Producer, Make_Cam, BoughtOn, Notes_Cam, ISOLimitGood, ISOLimitAcceptable)
        ///VALUES (@Producer, @Make, @BoughtOn, @Notes, @ISOLimitGood, @ISOLimitAcceptable);.
        /// </summary>
        public static string Save_Camera {
            get {
                return ResourceManager.GetString("Save_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE
        ///INTO EXIF WITH (HOLDLOCK) AS target
        ///USING (SELECT
        ///    @Make AS Make_EXIF,
        ///   @FNumber AS FNumber,
        ///   @ExposureTime AS ExposureTime,
        ///   @ISOValue AS ISOValue,
        ///   @Flash AS Flash,
        ///   @ExposureProgram AS ExposureProgram,
        ///   @FK_Pic_ID AS EXIF_FK_Pic_ID) AS source
        ///(Make_EXIF, FNumber, ExposureTime, ISOValue, Flash, ExposureProgram, EXIF_FK_Pic_ID)
        ///ON (target.EXIF_FK_Pic_ID = source.EXIF_FK_Pic_ID)
        ///WHEN MATCHED
        ///  THEN UPDATE
        ///      SET Make_EXIF = @Make,
        ///         FNumber = @FNumber,
        ///		 Expos [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Save_Exif {
            get {
                return ResourceManager.GetString("Save_Exif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE
        ///INTO IPTC WITH (HOLDLOCK) AS target
        ///USING (SELECT
        ///   @Keywords AS Keywords,
        ///   @ByLine AS ByLine,
        ///   @CopyrightNotice AS CopyrightNotice,
        ///   @Headline AS Headline,
        ///   @Caption AS Caption,
        ///   @FK_Pic_ID AS IPTC_FK_Pic_ID) AS source
        ///(Keywords, ByLine, CopyrightNotice, Headline, Caption, IPTC_FK_Pic_ID)
        ///ON (target.IPTC_FK_Pic_ID = source.IPTC_FK_Pic_ID)
        ///WHEN MATCHED
        ///  THEN UPDATE
        ///      SET Keywords = @Keywords,
        ///         ByLine = @ByLine,
        ///		 CopyrightNotice = @CopyrightNotice,
        ///		 Headline  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Save_Iptc {
            get {
                return ResourceManager.GetString("Save_Iptc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Photographers (FirstName, LastName, BirthDay, Notes_PG) 
        ///VALUES (@FirstName, @LastName, @BirthDay, @Notes).
        /// </summary>
        public static string Save_Photographer {
            get {
                return ResourceManager.GetString("Save_Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Pictures (FileName) 
        ///VALUES (@FileName);.
        /// </summary>
        public static string Save_Picture {
            get {
                return ResourceManager.GetString("Save_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///               &lt;tr&gt;
        ///                  &lt;th&gt;FirstName&lt;/th&gt;
        ///                  &lt;td&gt;Photographer_FirstName&lt;/td&gt;
        ///               &lt;/tr&gt;
        ///               &lt;tr&gt;
        ///                  &lt;th&gt;LastName&lt;/th&gt;
        ///                  &lt;td&gt;Photographer_LastName&lt;/td&gt;
        ///               &lt;/tr&gt;
        ///               &lt;tr&gt;
        ///                  &lt;th&gt;BirthDay&lt;/th&gt;
        ///                  &lt;td&gt;Photographer_BirthDay&lt;/td&gt;
        ///               &lt;/tr&gt;
        ///               &lt;tr&gt;
        ///                  &lt;th&gt;Notes&lt;/th&gt;
        ///                  &lt;td&gt;Photographer_Notes&lt;/td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string table_Camera {
            get {
                return ResourceManager.GetString("table_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;Make&lt;/th&gt;
        ///               &lt;td&gt;EXIF_Make&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;FNumber&lt;/th&gt;
        ///               &lt;td&gt;EXIF_FNumber&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;ExposureTime&lt;/th&gt;
        ///               &lt;td&gt;EXIF_ExposureTime&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;ISOValue&lt;/th&gt;
        ///               &lt;td&gt;EXIF_ISOValue&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;Flash&lt;/th&gt;
        ///               &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string table_EXIF {
            get {
                return ResourceManager.GetString("table_EXIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;Keywords&lt;/th&gt;
        ///               &lt;td&gt;IPTC_Keywords&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;ByLine&lt;/th&gt;
        ///               &lt;td&gt;IPTC_ByLine&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;CopyrightNotice&lt;/th&gt;
        ///               &lt;td&gt;IPTC_CopyrightNotice&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;Headline&lt;/th&gt;
        ///               &lt;td&gt;IPTC_Headline&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///               &lt;th&gt;Caption&lt;/th&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string table_IPTC {
            get {
                return ResourceManager.GetString("table_IPTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///               &lt;tr&gt;
        ///                  &lt;th&gt;FirstName&lt;/th&gt;
        ///                  &lt;td&gt;Photographer_FirstName&lt;/td&gt;
        ///               &lt;/tr&gt;
        ///               &lt;tr&gt;
        ///                  &lt;th&gt;LastName&lt;/th&gt;
        ///                  &lt;td&gt;Photographer_LastName&lt;/td&gt;
        ///               &lt;/tr&gt;
        ///               &lt;tr&gt;
        ///                  &lt;th&gt;BirthDay&lt;/th&gt;
        ///                  &lt;td&gt;Photographer_BirthDay&lt;/td&gt;
        ///               &lt;/tr&gt;
        ///               &lt;tr&gt;
        ///                  &lt;th&gt;Notes&lt;/th&gt;
        ///                  &lt;td&gt;Photographer_Notes&lt;/td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string table_Photographer {
            get {
                return ResourceManager.GetString("table_Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cameras
        ///SET Producer = @Producer, 
        ///	Make_Cam = @Make, 
        ///	BoughtOn = @BoughtOn, 
        ///	Notes_Cam = @Notes, 
        ///	ISOLimitGood = @ISOLimitGood, 
        ///	ISOLimitAcceptable = @ISOLimitAcceptable
        ///WHERE Cameras.Cam_ID = @Cam_ID;.
        /// </summary>
        public static string Update_Camera {
            get {
                return ResourceManager.GetString("Update_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE IPTC 
        ///SET IPTC.Keywords = @Keywords,
        ///	IPTC.ByLine = @ByLine,
        ///	IPTC.CopyrightNotice = @CopyrightNotice,
        ///	IPTC.Headline = @Headline,
        ///	IPTC.Caption = @Caption
        ///WHERE IPTC.IPTC_FK_Pic_ID = @Pic_ID;.
        /// </summary>
        public static string Update_IPTC {
            get {
                return ResourceManager.GetString("Update_IPTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Photographers 
        ///SET Photographers.FirstName = @FirstName,
        ///	Photographers.LastName = @LastName,
        ///	Photographers.BirthDay = @Birthday,
        ///	Photographers.Notes_PG = @Notes
        ///WHERE Photographers.PG_ID = @PG_ID;.
        /// </summary>
        public static string Update_Photographer {
            get {
                return ResourceManager.GetString("Update_Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Pictures
        ///SET Pictures.FK_Cam_ID = @Cam_ID
        ///WHERE Pictures.Pic_ID = @Pic_ID;.
        /// </summary>
        public static string Update_Pictures_Camera {
            get {
                return ResourceManager.GetString("Update_Pictures_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Pictures
        ///SET Pictures.FK_EXIF_ID = @EXIF_ID
        ///WHERE Pictures.Pic_ID = @Pic_ID;.
        /// </summary>
        public static string Update_Pictures_EXIF {
            get {
                return ResourceManager.GetString("Update_Pictures_EXIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Pictures
        ///SET Pictures.FK_IPTC_ID = @IPTC_ID
        ///WHERE Pictures.Pic_ID = @Pic_ID;.
        /// </summary>
        public static string Update_Pictures_IPTC {
            get {
                return ResourceManager.GetString("Update_Pictures_IPTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Pictures
        ///SET Pictures.FK_PG_ID = @PG_ID
        ///WHERE Pictures.Pic_ID = @Pic_ID;.
        /// </summary>
        public static string Update_Pictures_Photographer {
            get {
                return ResourceManager.GetString("Update_Pictures_Photographer", resourceCulture);
            }
        }
    }
}
